# .upptime/upptime.yml
# Complete configuration for Swappraise status monitoring

owner: a-grini
repo: swappraise-status

sites:
  - name: Production API
    url: https://app.swappraise.com/api/v1/health
    expectedStatusCodes:
      - 200
      - 201
    maxResponseTime: 5000

  - name: Development API
    url: https://dev.swappraise.com/api/v1/health
    expectedStatusCodes:
      - 200
      - 201
    maxResponseTime: 5000

status-website:
  # Custom domain
  cname: status.swappraise.com

  # Add your logo (optional)
  # logoUrl: https://app.swappraise.com/logo.png

  # Status page branding
  name: Swappraise Status
  introTitle: "**Swappraise** system status"
  introMessage: Real-time monitoring of Swappraise production and development environments. All systems operational.

  navbar:
    - title: Status
      href: /
    - title: Main App
      href: https://app.swappraise.com
    - title: GitHub
      href: https://github.com/a-grini/swappraise-status

  # Theme
  theme: dark

# Assignees for issues (you'll get notifications)
assignees:
  - a-grini

# User agent for requests
user-agent: upptime

# Check intervals
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"  # Check every 5 minutes

# Commit messages
commitMessages:
  readmeContent: ":pencil: Update summary in README [skip ci]"
  summaryJson: ":card_file_box: Update status summary [skip ci]"
  statusChange: "$EMOJI $SITE_NAME is $STATUS ($RESPONSE_CODE in $RESPONSE_TIME ms) [skip ci]"
  graphsUpdate: ":bento: Update graphs [skip ci]"

# Status website i18n
i18n:
  activeIncidents: Active Incidents
  allSystemsOperational: All Systems Operational
  incidentReport: "Incident #$NUMBER report →"
  activeIncidentSummary: Opened $DATE with $POSTS posts
  incidentTitle: Incident $NUMBER details
  incidentDetails: Incident details
  incidentFixed: Fixed
  incidentOngoing: Ongoing
  incidentOpenedAt: Opened at
  incidentClosedAt: Closed at
  incidentViewOnGitHub: View on GitHub
  incidentCommentSummary: Posted on $DATE by $AUTHOR
  incidentBack: ← Back to all incidents
  pastIncidents: Past Incidents
  pastIncidentsResolved: Resolved in $MINUTES minutes with $POSTS posts
  liveStatus: Live Status
  overallUptime: "Overall uptime: $UPTIME"
  overallUptimeTitle: Overall Uptime
  averageResponseTime: "Average response time: $TIMEms"
  averageResponseTimeTitle: Average Response Time
  sevelDayResponseTime: 7-day response time
  responseTimeMs: Response Time (ms)
  up: Up
  down: Down
  degraded: Degraded
  ms: ms
  loading: Loading
  navGitHub: GitHub
  footer: Powered by [Upptime](https://upptime.js.org)
  rateLimitExceededTitle: Rate limit exceeded
  rateLimitExceededIntro: You have exceeded the number of requests you can do in an hour, so you'll have to wait before trying again. Alternatively, you can add a GitHub Personal Access Token to continue to use this website.
  rateLimitExceededWhatDoesErrorMean: What does this error mean?
  rateLimitExceededErrorMeaning: This website uses the GitHub API to access real-time data about our websites' status. By default, GitHub allows each IP address 60 requests per hour, which you have consumed.
  rateLimitExceededErrorHowCanFix: How can I fix it?
  rateLimitExceededErrorFix: You can wait for another hour and your IP address's limit will be restored. Alternatively, you can add your GitHub Personal Access Token, which gives you an additional 5,000 requests per hour.
  rateLimitExceededGeneratePAT: Learn how to generate a Personal Access Token
  rateLimitExceededHasSet: You have a personal access token set.
  rateLimitExceededRemoveToken: Remove token
  rateLimitExceededGitHubPAT: GitHub Personal Access Token
  rateLimitExceededCopyPastePAT: Copy and paste your token
  rateLimitExceededSaveToken: Save token
  errorTitle: An error occurred
  errorIntro: An error occurred in trying to get the latest status details.
  errorText: You can try again in a few moments.
  errorHome: Go to Homepage
  pastScheduledMaintenance: Past Scheduled Maintenance
  scheduledMaintenance: Scheduled Maintenance
  scheduledMaintenanceSummary: Scheduled from $DATE_START to $DATE_END
  liveStatusReportLatestUpdates: Latest updates
  url: URL
